{exit_code: null, left_time: null, lunapark_id: null, lunapark_url: null, status_code: FINISHED,
  tank_msg: "Exception occurred:\n<type 'exceptions.RuntimeError'>: All connection\
    \ attempts failed for 0.0.0.0, use {phantom.connection_test: false} to disable\
    \ it\n  File \"/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py\"\
    , line 375, in run\n    self.core.plugins_configure()\n\n  File \"/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py\"\
    , line 245, in plugins_configure\n    plugin.configure()\n\n  File \"/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py\"\
    , line 72, in configure\n    self.phantom_config = self.phantom.config_file\n\n\
    \  File \"/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py\"\
    , line 81, in phantom\n    self._phantom.read_config()\n\n  File \"/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py\"\
    , line 95, in read_config\n    stream.read_config()\n\n  File \"/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py\"\
    , line 275, in read_config\n    self.address, do_test_connect, explicit_port)\n\
    \n  File \"/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py\"\
    , line 555, in resolve\n    raise RuntimeError(msg % address_str)\n"}
